"""corrections and notifications

Revision ID: 0160108ff983
Revises: b4af8f160dcc
Create Date: 2026-08-27 09:01:57.592633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use dialect-portable custom types (GUID, JSONType). Autogenerate
# renders them by their full path, so migrations must be able to resolve it.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '0160108ff983'
down_revision: Union[str, Sequence[str], None] = 'b4af8f160dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', app.db.types.JSONType(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('correction_requests',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', 'UNKNOWN', name='punchdirection'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='correctionstatus'), nullable=False),
    sa.Column('decided_by', app.db.types.GUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_note', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('punch_event_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['punch_event_id'], ['punch_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correction_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correction_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_correction_requests_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_correction_requests_shift_date'), ['shift_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_correction_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correction_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correction_requests_status'))
        batch_op.drop_index(batch_op.f('ix_correction_requests_shift_date'))
        batch_op.drop_index(batch_op.f('ix_correction_requests_org_id'))
        batch_op.drop_index(batch_op.f('ix_correction_requests_employee_id'))

    op.drop_table('correction_requests')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_org_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_category'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
