"""leave carry-forward runs

Revision ID: 57f593665a4d
Revises: 0160108ff983
Create Date: 2026-08-27 09:27:50.547149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use dialect-portable custom types (GUID, JSONType). Autogenerate
# renders them by their full path, so migrations must be able to resolve it.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '57f593665a4d'
down_revision: Union[str, Sequence[str], None] = '0160108ff983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_carry_forward_runs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('leave_type_id', app.db.types.GUID(), nullable=False),
    sa.Column('from_period', sa.String(length=16), nullable=False),
    sa.Column('to_period', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('available_before_cap', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'to_period', name='uq_carry_forward_once')
    )
    with op.batch_alter_table('leave_carry_forward_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_carry_forward_runs_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_carry_forward_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_carry_forward_runs_employee_id'))

    op.drop_table('leave_carry_forward_runs')
    # ### end Alembic commands ###
