"""phase1_leave

Revision ID: 62e3ba943f92
Revises: d1f4ff7b855c
Create Date: 2026-09-06 22:22:59.825215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use dialect-portable custom types (GUID, JSONType). Autogenerate
# renders them by their full path, so migrations must be able to resolve it.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '62e3ba943f92'
down_revision: Union[str, Sequence[str], None] = 'd1f4ff7b855c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_document_required', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('medical_document_deadline', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('medical_document_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('medical_document_submitted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED', 'CANCELLED', name='leavestatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED', 'CANCELLED', name='leavestatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('medical_document_submitted_at')
        batch_op.drop_column('medical_document_url')
        batch_op.drop_column('medical_document_deadline')
        batch_op.drop_column('medical_document_required')

    # ### end Alembic commands ###
