"""Add WFH tracking

Revision ID: 702aeb045fd0
Revises: de30c21fb328
Create Date: 2026-09-07 05:10:08.728907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use dialect-portable custom types (GUID, JSONType). Autogenerate
# renders them by their full path, so migrations must be able to resolve it.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '702aeb045fd0'
down_revision: Union[str, Sequence[str], None] = 'de30c21fb328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wfh_requests',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='correctionstatus'), nullable=False),
    sa.Column('decided_by_id', app.db.types.GUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wfh_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wfh_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wfh_requests_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_wfh_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('is_wfh_enabled')

    with op.batch_alter_table('wfh_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wfh_requests_org_id'))
        batch_op.drop_index(batch_op.f('ix_wfh_requests_employee_id'))

    op.drop_table('wfh_requests')
    # ### end Alembic commands ###
