"""Enrolment requests: employees submit, HR vouches

Revision ID: 8a4907d65f5a
Revises: a2eecb62ea48
Create Date: 2026-08-28 13:37:24.926201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use dialect-portable custom types (GUID, JSONType). Autogenerate
# renders them by their full path, so migrations must be able to resolve it.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '8a4907d65f5a'
down_revision: Union[str, Sequence[str], None] = 'a2eecb62ea48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolment_requests',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('photo_key', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', app.db.types.GUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrolment_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrolment_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrolment_requests_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolment_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrolment_requests_org_id'))
        batch_op.drop_index(batch_op.f('ix_enrolment_requests_employee_id'))

    op.drop_table('enrolment_requests')
    # ### end Alembic commands ###
