"""Location holds its own BSSIDs and presence policy

Revision ID: a2eecb62ea48
Revises: 57f593665a4d
Create Date: 2026-08-27 16:55:47.950941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use dialect-portable custom types (GUID, JSONType). Autogenerate
# renders them by their full path, so migrations must be able to resolve it.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'a2eecb62ea48'
down_revision: Union[str, Sequence[str], None] = '57f593665a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default on both, which autogenerate does not add. Without it,
    # adding a NOT NULL column to a table that already has rows fails outright
    # - and this table always has at least one row, because the office is
    # seeded before anyone can punch.
    #
    # The defaults are also the safe values to inherit: no registered access
    # points, and wifi_or_gps, which is the policy that passes on GPS alone.
    # An existing database therefore keeps behaving exactly as it did before
    # this migration ran, which is the property that makes it safe to apply to
    # the pilot's live data.
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'allowed_bssids', app.db.types.JSONType(),
            nullable=False, server_default='[]',
        ))
        batch_op.add_column(sa.Column(
            'presence_policy', sa.String(length=20),
            nullable=False, server_default='wifi_or_gps',
        ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('presence_policy')
        batch_op.drop_column('allowed_bssids')

    # ### end Alembic commands ###
