"""scheduled job runs

Revision ID: b2768267dc03
Revises: 8a4907d65f5a
Create Date: 2026-08-28 14:58:00.461261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use dialect-portable custom types (GUID, JSONType). Autogenerate
# renders them by their full path, so migrations must be able to resolve it.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'b2768267dc03'
down_revision: Union[str, Sequence[str], None] = '8a4907d65f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_job_runs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('job_name', sa.String(length=40), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('detail', app.db.types.JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name', 'dedupe_key', name='uq_job_once')
    )
    with op.batch_alter_table('scheduled_job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_job_runs_job_name'), ['job_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_job_runs_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_job_runs_org_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_job_runs_job_name'))

    op.drop_table('scheduled_job_runs')
    # ### end Alembic commands ###
