"""baseline: attendance, auth, face, leave

Revision ID: b4af8f160dcc
Revises: 
Create Date: 2026-08-27 08:39:40.050027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'b4af8f160dcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('settings', app.db.types.JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_org_id'), ['org_id'], unique=False)

    op.create_table('leave_policies',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('year_start_month', sa.Integer(), nullable=False),
    sa.Column('sandwich_rule', sa.Boolean(), nullable=False),
    sa.Column('backdate_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('leave_types',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('annual_quota', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('accrual_rule', sa.Enum('MONTHLY', 'ANNUAL', 'NONE', name='accrualrule'), nullable=False),
    sa.Column('carries_forward', sa.Boolean(), nullable=False),
    sa.Column('carry_cap', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('requires_proof', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_leave_type_code_per_org')
    )
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_types_org_id'), ['org_id'], unique=False)

    op.create_table('locations',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geofence_radius_m', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_org_id'), ['org_id'], unique=False)

    op.create_table('shift_templates',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('half_day_after_minutes', sa.Integer(), nullable=False),
    sa.Column('full_day_after_minutes', sa.Integer(), nullable=False),
    sa.Column('cutover_hour', sa.Integer(), nullable=False),
    sa.Column('working_days', app.db.types.JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_templates_org_id'), ['org_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('location_id', app.db.types.GUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('serial_no', sa.String(length=64), nullable=False),
    sa.Column('vendor', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('clock_offset_seconds', sa.Integer(), nullable=False),
    sa.Column('reports_direction', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', app.db.types.JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_no')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_org_id'), ['org_id'], unique=False)

    op.create_table('employees',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('emp_code', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department_id', app.db.types.GUID(), nullable=True),
    sa.Column('location_id', app.db.types.GUID(), nullable=True),
    sa.Column('manager_id', app.db.types.GUID(), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='employmenttype'), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('date_of_exit', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'emp_code', name='uq_employee_code_per_org')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_org_id'), ['org_id'], unique=False)

    op.create_table('holidays',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('location_id', app.db.types.GUID(), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_org_id'), ['org_id'], unique=False)

    op.create_table('attendance_day',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_template_id', app.db.types.GUID(), nullable=True),
    sa.Column('first_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_out_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'HALF_DAY', 'ABSENT', 'WEEKLY_OFF', 'HOLIDAY', 'ON_LEAVE', 'NOT_MARKED', name='attendancestatus'), nullable=False),
    sa.Column('punch_count', sa.Integer(), nullable=False),
    sa.Column('has_exception', sa.Boolean(), nullable=False),
    sa.Column('exception_note', sa.String(length=300), nullable=True),
    sa.Column('is_regularized', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'shift_date', name='uq_attendance_employee_date')
    )
    with op.batch_alter_table('attendance_day', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_day_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_attendance_org_date', ['org_id', 'shift_date'], unique=False)

    op.create_table('device_enrollments',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('device_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('device_user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'device_user_id', name='uq_device_user')
    )
    with op.batch_alter_table('device_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_enrollments_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_enrollments_employee_id'), ['employee_id'], unique=False)

    op.create_table('leave_accrual_runs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('leave_type_id', app.db.types.GUID(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('quota_at_run', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'period', 'month', name='uq_accrual_once')
    )
    with op.batch_alter_table('leave_accrual_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_accrual_runs_employee_id'), ['employee_id'], unique=False)

    op.create_table('leave_balances',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('leave_type_id', app.db.types.GUID(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('opening', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('accrued', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('used', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('encashed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'period', name='uq_balance_period')
    )
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_balances_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_balances_leave_type_id'), ['leave_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_balances_period'), ['period'], unique=False)

    op.create_table('mobile_devices',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('install_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('push_token', sa.String(length=400), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('install_id')
    )
    with op.batch_alter_table('mobile_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mobile_devices_employee_id'), ['employee_id'], unique=False)

    op.create_table('shift_assignments',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('shift_template_id', app.db.types.GUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_assignments_employee_id'), ['employee_id'], unique=False)

    op.create_table('users',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('actor_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', app.db.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('changes', app.db.types.JSONType(), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_org_id'), ['org_id'], unique=False)

    op.create_table('face_enrollments',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('photo_key', sa.String(length=400), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('enrolled_by', app.db.types.GUID(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['enrolled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_enrollments_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_enrollments_org_id'), ['org_id'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('leave_type_id', app.db.types.GUID(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('half_day_start', sa.Boolean(), nullable=False),
    sa.Column('half_day_end', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), nullable=False),
    sa.Column('days_consumed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('approver_id', app.db.types.GUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_note', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_from_date'), ['from_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_to_date'), ['to_date'], unique=False)

    op.create_table('punch_events',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=True),
    sa.Column('device_id', app.db.types.GUID(), nullable=True),
    sa.Column('source', sa.Enum('GATE_DEVICE', 'MOBILE_APP', 'WEB_KIOSK', 'MANUAL', 'IMPORT', name='punchsource'), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', 'UNKNOWN', name='punchdirection'), nullable=False),
    sa.Column('event_ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('photo_key', sa.String(length=400), nullable=True),
    sa.Column('geofence_ok', sa.Boolean(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('face_ok', sa.Boolean(), nullable=True),
    sa.Column('face_similarity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rejection_reason', sa.String(length=200), nullable=True),
    sa.Column('mobile_device_id', app.db.types.GUID(), nullable=True),
    sa.Column('raw_payload', app.db.types.JSONType(), nullable=False),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.Column('is_unmatched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['mobile_device_id'], ['mobile_devices.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_hash', name='uq_punch_dedupe')
    )
    with op.batch_alter_table('punch_events', schema=None) as batch_op:
        batch_op.create_index('ix_punch_employee_ts', ['employee_id', 'event_ts_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_punch_events_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_punch_events_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_punch_org_ts', ['org_id', 'event_ts_utc'], unique=False)

    op.create_table('refresh_sessions',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('install_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_install_id'), ['install_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_install_id'))

    op.drop_table('refresh_sessions')
    with op.batch_alter_table('punch_events', schema=None) as batch_op:
        batch_op.drop_index('ix_punch_org_ts')
        batch_op.drop_index(batch_op.f('ix_punch_events_org_id'))
        batch_op.drop_index(batch_op.f('ix_punch_events_employee_id'))
        batch_op.drop_index('ix_punch_employee_ts')

    op.drop_table('punch_events')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_to_date'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_status'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_org_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_from_date'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_employee_id'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('face_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_enrollments_org_id'))
        batch_op.drop_index(batch_op.f('ix_face_enrollments_employee_id'))

    op.drop_table('face_enrollments')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))

    op.drop_table('users')
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_assignments_employee_id'))

    op.drop_table('shift_assignments')
    with op.batch_alter_table('mobile_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mobile_devices_employee_id'))

    op.drop_table('mobile_devices')
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_balances_period'))
        batch_op.drop_index(batch_op.f('ix_leave_balances_leave_type_id'))
        batch_op.drop_index(batch_op.f('ix_leave_balances_employee_id'))

    op.drop_table('leave_balances')
    with op.batch_alter_table('leave_accrual_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_accrual_runs_employee_id'))

    op.drop_table('leave_accrual_runs')
    with op.batch_alter_table('device_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_enrollments_employee_id'))
        batch_op.drop_index(batch_op.f('ix_device_enrollments_device_id'))

    op.drop_table('device_enrollments')
    with op.batch_alter_table('attendance_day', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_org_date')
        batch_op.drop_index(batch_op.f('ix_attendance_day_org_id'))

    op.drop_table('attendance_day')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_org_id'))
        batch_op.drop_index(batch_op.f('ix_holidays_location_id'))
        batch_op.drop_index(batch_op.f('ix_holidays_day'))

    op.drop_table('holidays')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_org_id'))
        batch_op.drop_index(batch_op.f('ix_employees_email'))

    op.drop_table('employees')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_org_id'))

    op.drop_table('devices')
    with op.batch_alter_table('shift_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_templates_org_id'))

    op.drop_table('shift_templates')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_org_id'))

    op.drop_table('locations')
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_types_org_id'))

    op.drop_table('leave_types')
    op.drop_table('leave_policies')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_org_id'))

    op.drop_table('departments')
    op.drop_table('organizations')
    # ### end Alembic commands ###
