"""Add slack sync columns to leave_requests

Revision ID: d1f4ff7b855c
Revises: b2768267dc03
Create Date: 2026-08-31 18:25:56.769333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use dialect-portable custom types (GUID, JSONType). Autogenerate
# renders them by their full path, so migrations must be able to resolve it.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'd1f4ff7b855c'
down_revision: Union[str, Sequence[str], None] = 'b2768267dc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_message_ts', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('slack_channel_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('slack_channel_id')
        batch_op.drop_column('slack_message_ts')

    # ### end Alembic commands ###
