"""Add category to CorrectionRequest and correction_limit to Employee

Revision ID: de30c21fb328
Revises: 62e3ba943f92
Create Date: 2026-09-07 00:14:25.898140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use dialect-portable custom types (GUID, JSONType). Autogenerate
# renders them by their full path, so migrations must be able to resolve it.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'de30c21fb328'
down_revision: Union[str, Sequence[str], None] = '62e3ba943f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correction_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=120), server_default='Other', nullable=False))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correction_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('correction_limit')

    with op.batch_alter_table('correction_requests', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
