"""add_shift_groups_and_leave_category

Revision ID: f16cdec5d72f
Revises: 702aeb045fd0
Create Date: 2026-09-07 18:29:08.578455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use dialect-portable custom types (GUID, JSONType). Autogenerate
# renders them by their full path, so migrations must be able to resolve it.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'f16cdec5d72f'
down_revision: Union[str, Sequence[str], None] = '702aeb045fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_groups',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('org_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('shift_template_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_groups_org_id'), ['org_id'], unique=False)

    op.create_table('shift_group_members',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('shift_group_id', app.db.types.GUID(), nullable=False),
    sa.Column('employee_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_group_id'], ['shift_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_group_id', 'employee_id', name='uq_shift_group_member')
    )
    with op.batch_alter_table('shift_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_group_members_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_group_members_shift_group_id'), ['shift_group_id'], unique=False)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('shift_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_group_members_shift_group_id'))
        batch_op.drop_index(batch_op.f('ix_shift_group_members_employee_id'))

    op.drop_table('shift_group_members')
    with op.batch_alter_table('shift_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_groups_org_id'))

    op.drop_table('shift_groups')
    # ### end Alembic commands ###
